name = "url-metascraper"
main = "src/index.js"
compatibility_date = "2024-12-26"
compatibility_flags = ["nodejs_compat"]

# 同時支援 workers.dev 和自訂域名
routes = [
  { pattern = "happylee.app/scraper/*", zone_name = "happylee.app" }
]
